spring:
  mvc:
    static-path-pattern: /content/**
  web:
    resources:
      static-locations: "file:${file.path}"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  flyway:
    locations: "classpath:/h2/db/migration"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


server:
  port: 8090
  image:
    path: "http://3.111.232.13:8090/content/"
file:
  path: "D:\\image_files\\"
  type: "images"

auth:
  whitelist: "/v3/api-docs/**,/swagger-ui/**,/h2-console/**,/api/v1/login/**,/api/v1/firmProfile/create**/**,/api/v1/personalProfile/create**/**,/file/**,/api/master/search**/**,/content/**"



