spring:
  datasource:
    url: jdbc:mysql://3.111.232.13:3306/vire
    username: root
    password: NBpAJrQj5A2PYmJG
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8090

file:
  path: "D:\\image_files\\"
  type: "images"