spring:
  mvc:
    static-path-pattern: /content/**
  web:
    resources:
      static-locations: "file:${file.path}"
  datasource:
    url: jdbc:mysql://3.111.232.13:3306/vire
    username: root
    password: NBpAJrQj5A2PYmJG
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8090
  image:
    path: "http://3.111.232.13:8082/content/"

file:
  path: "/home/ubuntu/vireapp/files/"
  type: "images"

auth:
  whitelist: "/admin/**,/v3/api-docs/**,/swagger-ui/**,/h2-console/**,/api/v1/login/**,/api/v1/firmProfile/create**/**,/api/v1/personalProfile/create**/**,/file/**,/api/master/search**/**,/content/**,/api/locationmaster/**"
