spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 5000

image:
  path: "D:\\image_files\\"