spring:
  mvc:
    static-path-pattern: /content/**
  web:
    resources:
      static-locations: "file:${file.path}"
  datasource:
    url: jdbc:mysql://3.111.232.13:3306/viretest
    username: vire
    password: vire
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8090
  image:
    path: "http://localhost:8090/content/"
file:
  path: "D:\\image_files\\"
  type: "images"

auth:
  whitelist: "/**"