spring:
  datasource:
    url: jdbc:mysql://viredb.cjkvnr9lbjyl.ap-south-1.rds.amazonaws.com:3306/vire
    username: root
    password: Password_v
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8080

file:
  path: "D:\\image_files\\"
  type: "images"